### ISSUE TITLE
Bug: No canonical tag added to home page

### ISSUE THREAD

**Issue by Undistraction** [NickCis/gatsby-plugin-react-helmet-canonical-urls#18]
With the following config:
```
resolve: `gatsby-plugin-react-helmet-canonical-urls`,
  options: {
    siteUrl: `https://www.example.org.uk`,
    exclude: [`/blah`],
  },
```
No canonical tag is added to the home page.

**Comment by rodrigograca31** [comment]
~~Same here. its actually not added anywhere.~~

Actually it works. But only on `gatsby build` and not on `gatsby develop` like I was expecting

**Comment by ahmadkhalaf1** [comment]
i also have this issue , on production build and development , only home page is missing canonical url , how can we solve this?

**Comment by NickCis** [comment]
Could you provide a small reproduction example?

**Comment by ansmlc** [comment]
Is this resolved?

**Comment by NickCis** [comment]
@ansmlc . No one has provided an example in order to reproduce the error and no push request fixing it has been sent. I really don't know if the problem even existed.

**Comment by ansmlc** [comment]
@NickCis Ok, fair enough. Otherwise, do you consider this plugin still a viable alternative to` gatsby-plugin-canonical-urls`? 

We're having some SEO issues with canonical urls while using it along with `gatsby-plugin-react-helmet` so thinking about giving this plugin a shot to see if it helps.

**Comment by NickCis** [comment]
You could give it a try, I really don't know. I'm not using gatsby on a daily basis, so, really don't have a strong opinion about it :/. Sorry!

**Comment by DPro23** [comment]
I checked right now and it's true. It's also removing the canonical tag to some random pages.

Also the exclude is amazing how is the only one stuff without any example.

Regex can have multiple ways how to be implemented.. here I can't let work also excludes with regex. But of course, it's the other issue opened

**Comment by NickCis** [comment]
@DPro23 It's open source, if you find a problem you can fix it. As you are saying that there is no `exclude` example, perhaps you could write one. Nobody owes you nothing, if you don't like it and you are not willing to help in any way, you should stay quiet.

As I've said earlier, no one has ever provided a repo in order to reproduce the error. I'm not being paid for searching and fixing bugs, so, if people that have problems with the code don't cooperate in a friendly manner, I won't do much, I'm not obliged to fix anything. The code worked for my case of use, so for me its ok.

**Comment by DPro23** [comment]
@NickCis you answer is a usefull as mine... 

If you took your time to answer "I let it work", then please share your working regex. It's the only one thing not working or, as you sayed, that it's not clear how to let it work.

Thank you

**Comment by ahmadkhalaf1** [comment]
> @DPro23 It's open source, if you find a problem you can fix it. As you are saying that there is no `exclude` example, perhaps you could write one. Nobody owes you nothing, if you don't like it and you are not willing to help in any way, you should stay quiet.
> 
> As I've said earlier, no one has ever provided a repo in order to reproduce the error. I'm not being paid for searching and fixing bugs, so, if people that have problems with the code don't cooperate in a friendly manner, I won't do much, I'm not obliged to fix anything. The code worked for my case of use, so for me its ok.

relax dude , you dont have to be toxic 
its simple , if u can/want help then do , if not just ignore it without attacking someone who is asking for help  , dont just assume that every person is able to write code or help , maybe he is a biggener ? fresh graduate ? 
chill out its not a big deal that he asked some questions .

**Comment by ahmadkhalaf1** [comment]
wow very mature :) go back to school kid 
and delete this comment too _!_
