### ISSUE TITLE
Please Don't Force Trailing Slash Onto Homepage URL

### ISSUE THREAD

**Issue by Undistraction** [NickCis/gatsby-plugin-react-helmet-canonical-urls#4]
This plugin adds a trailing slash to the homepage URL, however the homepage is often treated as an exception and even if all other pages use a trailing slash, the homepage shouldn't. 

This behaviour should probably be opt-in only or the plugin should support opting out.

**Comment by NickCis** [comment]
Why are you saying that the homepage shouldn't have a trailing slash? Could you link the Google recommendation about that?.

If you want to exclude the homepage from adding a canonical link, you can use the `exclude` option. An empty string (`''`) or a slash (`'/'`) would be treated as the homepage.

**Comment by Undistraction** [comment]
It's pretty much up to a developer whether they want the canonical version of their homepage to have a trailing slash or not. You will find plenty of discussion online about which is best, but usually the answer is whichever the developer prefers. Unfortunately this plugin imposes the decision on the developer by adding a trailing slash even if one isn't present.

**Comment by NickCis** [comment]
Have you read the motivation?:

> gatsby-plugin-canonical-urls and gatsby-plugin-react-helmet are plugins that do not always play well together. The first one always inserts a default canonical url, but doesn't allow to override that value in an easy way. When trying to use react helmet to override gatsby-plugin-canonical-urls default url, you will end up with two canonical tags.
>
> **This plugin, as writes the default canonical url using react helmet, allows to override default canonical url just using the standard react helmet api.**

The plugin doesn't force the developer to have a particular canonical link on any page, if you want to override it, just set the canonical link of that page using the [Helmet api](https://github.com/nfl/react-helmet) and as the plugin inserts the link (via the Helmet api) on a higher level, it will have a lower priority, ie, your link exception will be used.

The plugin has two modes with trailing slash (default) and without trailing slash (`noTrailingSlash: true`). If you want to have a mixed mode, as you are asking for the home page, you have the possibility, as it's explained in _motivation_, to override the default link using Helmet API.
