### ISSUE TITLE
Don't Include Query String In Hydrated or Client-rendered Canonical Tags

### ISSUE THREAD

**Issue by Undistraction** [NickCis/gatsby-plugin-react-helmet-canonical-urls#5]
The current behaviour of the plugin means that even though the correct canonical URL is rendered during the build, any transient query string values are included in the canonical URL when it is rendered on the client, so for an article page as an example, the server-rendered page will have a canonical URL of `https://example.com/articles/alpha`, however if someone lands on the page with a query string included (for example including a Google UTM param for tracking),  the canonical URL will be changed during hydration to `https://example.com/articles/alpha/?utm_source=instagram`. 

Although sometimes query string params are used for representing state, in many cases they are ephemeral, and in fact ensuring query strings do not lead to multiple versions of a URL being indexed is one of the main uses of canonical tags.

I would imagine that the great majority of users of Gatsby would prefer to ignore query strings in canonical tags, so I believe the plugin should ignore query strings entirely when hydrating or rendering pages on the client.

**Comment by NickCis** [comment]
Althought, [when indexing Google only reads canonical, meta from the non-js version](https://youtu.be/PFwUbgvpdaQ?t=914), this could be a good improvement.

You could add a configuration option `withSearch` and `withHash` for allowing to use the search and hash strings. As you are suggesting, a good default could be not to include them.

Thanks for pointing this up, I'm willing to see the PR!.

Thanks :)

**Comment by NickCis** [comment]
This has been developed under #12 PR.
