### ISSUE TITLE
Allow using a glob for exclude

### ISSUE THREAD

**Issue by me4502** [NickCis/gatsby-plugin-react-helmet-canonical-urls#7]
Currently you need to explicitly specify every page to exclude, which makes no sense for dynamically generated pages.

A common use case would be ignoring AMP pages, as the gatsby AMP plugin already includes canonical tags in the AMP pages. Being able to exclude all pages ending in /amp/ using glob/regex matching would fix this issue.

**Comment by NickCis** [comment]
Great idea!, The `exclude` option could also allow passing regex.

If you have some free time, it would be great if can send the PR!

**Comment by ArthurHwang** [comment]
I have this exact issue.

I have 3000 amp pages that I need to exclude the canonical from.  Is there another way to do this currently?

**Comment by NickCis** [comment]
The last version published (`1.3.0`) allows to use `RegExp` on the `exclude` array to achieve this feature.
